language: objective-c
install:
  - npm install
before_script:
  - chmod +x ./ios/RockCer/add-key.sh
  - cd ./ios/RockCer
  - ./add-key.sh
  - cd -
script:
  - xcodebuild -project "./ios/learnRN.xcodeproj" -scheme "learnRN" archive -archivePath "./buildIOSTemp/learnRN_0.0.1.xcarchive" -quiet
  - xcodebuild -exportArchive -archivePath "./buildIOSTemp/learnRN_0.0.1.xcarchive" -exportPath "./buildIOSTemp/learnRN_0.0.1" -exportOptionsPlist "exportTestOptions.plist" -quiet
