language: android
# - tools
# - platform-tools
sudo: false

before_install: #1.1
  - nvm install 6
  - node --version
install: #1.2
  - npm install
android:
  components:
  - build-tools-23.0.1
  - android-23 
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
cache:
  directories:
  - node_modules
script:
  - cd android && ./gradlew clean
  - ./gradlew assembleRelease #3
  - cd ./app/build/outputs/apk
  - ls
  # - curl -F 'file=@android/app/build/outputs/apk/app-release-1.0.apk' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
